const BAD_REQUEST = 400;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const DEFAULT = 500;
const UNAUTHORIZED = 401;
const CONFLICT = 409;

module.exports = {
  BAD_REQUEST,
  FORBIDDEN,
  NOT_FOUND,
  DEFAULT,
  UNAUTHORIZED,
  CONFLICT,
};
